services:
  postgres:
    image: postgres:15
    container_name: tracker-postgres
    restart: always
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    depends_on:
      postgres:
        condition: service_healthy

  gateway:
    build: ./api-gateway
    container_name: tracker-gateway
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
    env_file: .env

  activity:
    build: ./activity-service
    container_name: tracker-activity
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      gateway:
        condition: service_healthy
    env_file: .env

  gamification:
    build: ./gamification-service
    container_name: tracker-gamification
    ports:
      - "8082:8082"
    depends_on:
      postgres:
        condition: service_healthy
      eureka-server:
        condition: service_healthy
      activity:
        condition: service_healthy
      gateway:
        condition: service_healthy
    env_file: .env

volumes:
  postgres_data: