global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'eureka-server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8761' ]
        labels:
          application: 'eureka-server'

  - job_name: 'api-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8080' ]
        labels:
          application: 'api-gateway'

  - job_name: 'activity-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          application: 'activity-service'

  - job_name: 'gamification-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]
        labels:
          application: 'gamification-service'

  - job_name: 'rabbitmq'
    metrics_path: '/metrics'
    static_configs:
      - targets: [ 'host.docker.internal:15692' ]
        labels:
          application: 'rabbitmq'